# frozen_string_literal: true

require 'CryptoPriceFinder'
puts "Monero: #{CryptoPriceFinder.monero(6.6)}"
puts "Bitcoin: #{CryptoPriceFinder.bitcoin(3)}"
puts "Stellar: #{CryptoPriceFinder.stellar(4)}"
puts "DogeCoin: #{CryptoPriceFinder.dogecoin(4)}"
puts "Etherum: #{CryptoPriceFinder.ethereum(4)}"
puts "Ripple: #{CryptoPriceFinder.ripple(5)}"
puts "Tron: #{CryptoPriceFinder.tron(4)}"
puts "Solana: #{CryptoPriceFinder.solana(4)}"
puts "BitcoinCash: #{CryptoPriceFinder.bitcoin_cash(4)}"
puts "PEPE: #{CryptoPriceFinder.pepe(3)}"
puts "Litecoin: #{CryptoPriceFinder.litecoin(3)}"
puts "Polkadot: #{CryptoPriceFinder.polkadot(3)}"
puts "ChainLink: #{CryptoPriceFinder.chainlink(2)}"
puts "Shiba Inu: #{CryptoPriceFinder.shiba_inu(3)}"
puts "Filecoin: #{CryptoPriceFinder.filecoin(4)}"
puts "BAT: #{CryptoPriceFinder.bat(5)}"
puts "BNB: #{CryptoPriceFinder.bnb(6554)}"
puts "Bonk: #{CryptoPriceFinder.bonk(444_444)}"
puts "Ravencoin: #{CryptoPriceFinder.ravencoin(887)}"
